export const SET_SHIPMENT_METHOD = "SET_SHIPMENT_METHOD";
export const CHANGE_SELECTED = "CHANGE_SELECTED";
export const DESTROY_CHECKOUT_SHIPPING = "DESTROY_CHECKOUT_SHIPPING";
export const EDIT_SHIPPING_METHOD = "EDIT_SHIPPING_METHOD";
export const DELETE_SHIPPING_METHOD = "DELETE_SHIPPING_METHOD";
