export const SET_SHIPMENT_METHOD = "SET_SHIPMENT_METHOD";
export const CHANGE_SELECTED = "CHANGE_SELECTED";
export const DESTROY_CHECKOUT_SHIPPING = "DESTROY_CHECKOUT_SHIPPING";

export const ADD_SHIPPING_METHOD = "ADD_SHIPPING_METHOD";
export const EDIT_SHIPPING_METHOD = "EDIT_SHIPPING_METHOD";
export const DELETE_SHIPPING_METHOD = "DELETE_SHIPPING_METHOD";

export const ADD_SHIPPING_PROVIDER = "ADD_SHIPPING_PROVIDER";
export const UPDATE_SHIPPING_PROVIDER = "UPDATE_SHIPPING_PROVIDER";
export const REMOVE_SHIPPING_PROVIDER = "REMOVE_SHIPPING_PROVIDER";
