export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const APPROVE_COMMENT = "APPROVE_COMMENT";

export const HANDLE_KEY_COMMAND = "HANDLE_KEY_COMMAND";
export const TOGGLE_BLOCK_TYPE = "TOGGLE_BLOCK_TYPE";
export const TOGGLE_INLINE_STYLE = "TOGGLE_INLINE_STYLE";
