export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const APPROVE_COMMENT = "APPROVE_COMMENT";

export const TOGGLE_BOLD = "TOGGLE_BOLD";
