export const TOGGLE_COMMENT_WINDOW = "TOGGLE_COMMENT_WINDOW";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const APPROVE_COMMENT = "APPROVE_COMMENT";
