export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";
//export const GET_CARTCOUNT = "GET_CARTCOUNT";
export const TOGGLE_CART = "TOGGLE_CART";

export const OPEN_SETTINGS = "OPEN_SETTINGS";
export const CLOSE_SETTINGS = "CLOSE_SETTINGS";
