export const LOGIN = "LOGIN";
export const LOGIN_WITH_SERVICE = "LOGIN_WITH_SERVICE";
export const LOGOUT = "LOGOUT";
export const CREATE_USER = "CREATE_USER";

// Profile
export const CHANGE_PROFILE_FIELDS = "CHANGE_PROFILE_FIELDS";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

// AddressBook
export const CHANGE_ADDRESSBOOK = "CHANGE_ADDRESSBOOK";
export const CHANGE_CURRENT_VIEW = "CHANGE_CURRENT_VIEW";
export const DESTROY_ADDRESSBOOK = "DESTROY_ADDRESSBOOK";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const CHANGE_SHIPPING_ADDRESS = "CHANGE_SHIPPING_ADDRESS";
export const CHANGE_BILLING_ADDRESS = "CHANGE_BILLING_ADDRESS";
