export const LOGIN = "LOGIN";
export const LOGIN_WITH_SERVICE = "LOGIN_WITH_SERVICE";
export const LOGOUT = "LOGOUT";
export const CREATE_USER = "CREATE_USER";

export const CHANGE_PROFILE_FIELDS = "CHANGE_PROFILE_FIELDS";
