export const CHANGE_CART_WORKFLOW = "CHANGE_CART_WORKFLOW";
export const UPDATE_CART_WORKFLOW = "CHANGE_CART_WORKFLOW";
export const DESTROY_CHECKOUT = "DESTROY_CHECKOUT";

export const CONTINUE_AS_GUEST = "CONTINUE_AS_GUEST";
export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";

export const ADD_ORDER_EMAIL = "ADD_ORDER_EMAIL";

export const UPDATE_CART_NOTE = "UPDATE_CART_NOTE";
export const ROLLBACK_CART_NOTE_STATE = "ROLLBACK_CART_NOTE_STATE";
