export const CHANGE_CART_WORKFLOW = "CHANGE_CART_WORKFLOW";
export const UPDATE_CART_WORKFLOW = "CHANGE_CART_WORKFLOW";
export const DESTROY_CHECKOUT = "DESTROY_CHECKOUT";

export const CONTINUE_AS_GUEST = "CONTINUE_AS_GUEST";
export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";
