export const SET_PRODUCTS_SCROLL_LIMIT = "SET_PRODUCTS_SCROLL_LIMIT";
export const SET_PRODUCT_ID = "SET_PRODUCT_ID";
export const SET_VARIANT_ID = "SET_VARIANT_ID";
export const TOGGLE_PRODUCT_VISIBILITY = "TOGGLE_PRODUCT_VISIBILITY";
export const CHANGE_PRODUCT_FIELD = "CHANGE_PRODUCT_FIELD";
export const UPDATE_PRODUCT_FIELD = "UPDATE_PRODUCT_FIELD";
