export const SET_PRODUCTS_SCROLL_LIMIT = "SET_PRODUCTS_SCROLL_LIMIT";

export const SET_PRODUCT_ID = "SET_PRODUCT_ID";
export const SET_VARIANT_ID = "SET_VARIANT_ID";
export const CHANGE_SELECTED_VARIANT_ID = "CHANGE_SELECTED_VARIANT_ID";
export const DESTROY_SELECTED_IDS = "DESTROY_SELECTED_IDS";

export const CHANGE_PRODUCT_FIELD = "CHANGE_PRODUCT_FIELD";
export const UPDATE_PRODUCT_FIELD = "UPDATE_PRODUCT_FIELD";
export const ROLLBACK_FIELD_STATE = "ROLLBACK_FIELD_STATE";

export const UPLOAD_MEDIA = "UPLOAD_MEDIA";
export const REMOVE_MEDIA = "REMOVE_MEDIA";
export const SYNC_MEDIA = "SYNC_MEDIA"; // with minimongo
export const MOVE_MEDIA = "MOVE_MEDIA";
export const DROP_MEDIA = "DROP_MEDIA";
export const DESTROY_MEDIA = "DESTROY_MEDIA";

export const TOGGLE_PRODUCT_VISIBILITY = "TOGGLE_PRODUCT_VISIBILITY";
export const CLONE_PRODUCTS = "CLONE_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CHANGE_PRODUCT_WEIGHT = "CHANGE_PRODUCT_WEIGHT";

// TODO: should be TOGGLE?
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const UNSELECT_PRODUCT = "UNSELECT_PRODUCT";
export const FLUSH_SELECTED_PRODUCTS = "FLUSH_SELECTED_PRODUCTS";

export const CHANGE_TAG = "CHANGE_TAG";
export const CHANGE_NEW_TAG = "CHANGE_NEW_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const REMOVE_TAG = "REMOVE_TAG";
export const SYNC_TAGS = "SYNC_TAGS";
export const MOVE_TAG = "MOVE_TAG";
export const DROP_TAG = "DROP_TAG";
export const DESTROY_TAGS = "DESTROY_TAGS";
export const CLEAR_NEW_TAG_NAME = "CLEAR_NEW_TAG_NAME";
export const LOAD_SUGGESTIONS_BEGIN = "LOAD_SUGGESTIONS_BEGIN";
export const UPDATE_SUGGESTIONS = "UPDATE_SUGGESTIONS";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";

export const UPDATE_METAFIELD = "UPDATE_METAFIELD";
export const REMOVE_METAFIELDS = "REMOVE_METAFIELDS";

export const GET_TOP_VARIANTS = "GET_TOP_VARIANTS";
export const ADD_TOP_VARIANT = "ADD_TOP_VARIANT";
export const CREATE_TOP_VARIANT = "CREATE_TOP_VARIANT";
export const REMOVE_TOP_VARIANT = "REMOVE_TOP_VARIANT";
export const DESTROY_TOP_VARIANTS = "DESTROY_TOP_VARIANTS";
export const CHANGE_VARIANT_FORM_VISIBILITY = "CHANGE_VARIANT_FORM_VISIBILITY";
export const CREATE_CHILD_VARIANT = "CREATE_CHILD_VARIANT";
export const CLONE_VARIANT = "CLONE_VARIANT";
export const DELETE_VARIANT = "DELETE_VARIANT";
export const UPDATE_VARIANT = "UPDATE_VARIANT";
export const SYNC_WITH_TITLE = "SYNC_WITH_TITLE";

export const CHANGE_ADD_TO_CART_QUANTITY = "CHANGE_ADD_TO_CART_QUANTITY";
export const INCREMENT_ADD_TO_CART_QUANTITY = "INCREMENT_ADD_TO_CART_QUANTITY";
export const DECREMENT_ADD_TO_CART_QUANTITY = "DECREMENT_ADD_TO_CART_QUANTITY";
export const DESTROY_ADD_TO_CART_QUANTITY = "DESTROY_ADD_TO_CART_QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
