export const SET_PRODUCTS_SCROLL_LIMIT = "SET_PRODUCTS_SCROLL_LIMIT";

export const SET_PRODUCT_ID = "SET_PRODUCT_ID";
export const SET_VARIANT_ID = "SET_VARIANT_ID";

export const CHANGE_PRODUCT_FIELD = "CHANGE_PRODUCT_FIELD";
export const UPDATE_PRODUCT_FIELD = "UPDATE_PRODUCT_FIELD";
export const ROLLBACK_FIELD_STATE = "ROLLBACK_FIELD_STATE";

export const UPLOAD_MEDIA = "UPLOAD_MEDIA";
export const REMOVE_MEDIA = "REMOVE_MEDIA";
export const SYNC_MEDIA = "SYNC_MEDIA"; // with minimongo
export const MOVE_MEDIA = "MOVE_MEDIA";

export const TOGGLE_PRODUCT_VISIBILITY = "TOGGLE_PRODUCT_VISIBILITY";
export const CLONE_PRODUCTS = "CLONE_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CHANGE_PRODUCT_WEIGHT = "CHANGE_PRODUCT_WEIGHT";

// TODO: should be TOGGLE?
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const UNSELECT_PRODUCT = "UNSELECT_PRODUCT";
export const FLUSH_SELECTED_PRODUCTS = "FLUSH_SELECTED_PRODUCTS";

export const CHANGE_TAG = "CHANGE_TAG";
export const CHANGE_NEW_TAG = "CHANGE_NEW_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const REMOVE_TAG = "REMOVE_TAG";
export const CLEAR_NEW_TAG_NAME = "CLEAR_NEW_TAG_NAME";
export const LOAD_SUGGESTIONS_BEGIN = "LOAD_SUGGESTIONS_BEGIN";
export const UPDATE_SUGGESTIONS = "UPDATE_SUGGESTIONS";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";