export const GET_PACKAGES = "GET_PACKAGES";
export const TOGGLE_PACKAGE = "TOGGLE_PACKAGE";

export const OPEN_SETTINGS = "OPEN_SETTINGS";
export const CLOSE_SETTINGS = "CLOSE_SETTINGS";

export const SUBMIT_SHOP_FORM = "SUBMIT_SHOP_FORM";

export const SUBMIT_OAUTH_SERVICE_FORM = "SUBMIT_OAUTH_SERVICE_FORM";
export const TOGGLE_OAUTH_SERVICE = "TOGGLE_OAUTH_SERVICE";

export const TOGGLE_PERMISSION = "TOGGLE_PERMISSION";
export const TOGGLE_PERMISSION_SETTINGS = "TOGGLE_PERMISSION_SETTINGS";
