export const GET_PACKAGES = "GET_PACKAGES";
export const TOGGLE_PACKAGE = "TOGGLE_PACKAGE";

export const SUBMIT_SHOP_FORM = "SUBMIT_SHOP_FORM";

export const SUBMIT_OAUTH_SERVICE_FORM = "SUBMIT_OAUTH_SERVICE_FORM";
export const TOGGLE_OAUTH_SERVICE = "TOGGLE_OAUTH_SERVICE";

export const SUBMIT_ADD_MEMBER_FORM = "SUBMIT_ADD_MEMBER_FORM";

export const TOGGLE_PERMISSION = "TOGGLE_PERMISSION";
export const TOGGLE_PERMISSION_SETTINGS = "TOGGLE_PERMISSION_SETTINGS";

export const TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE";

export const TOGGLE_CARD = "TOGGLE_CARD";

export const TOGGLE_COMMENTS_MODERATION = "TOGGLE_COMMENTS_MODERATION";

// orders
export const CHANGE_ORDER_FILTER = "CHANGE_ORDER_FILTER";
export const START_ORDER_PROCESSING = "START_ORDER_PROCESSING";

export const APPROVE_PAYMENT = "APPROVE_PAYMENT";
export const CAPTURE_PAYMENT = "CAPTURE_PAYMENT";
export const REFUND_PAYMENT = "REFUND_PAYMENT";
export const MAKE_ADJUSTMENTS = "MAKE_ADJUSTMENTS";
